name: Laravel Backend Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $USERNAME@$SERVER_IP << 'EOF'
            echo "cd into project directory..."
            cd /var/www/chatbots/backend

            echo "Check if the repository is already cloned..."
            if [ ! -d ".git" ]; then
              sudo -u deployer git clone https://github.com/hosseinmirzapur/chatbot-manager.git .
            else
              sudo -u deployer git pull origin main
            fi

            echo "Copy .env file to the project directory..."
            sudo -u deployer cp /var/www/chatbots/.env /var/www/chatbots/backend/.env

            echo "Install dependencies..."
            sudo -u deployer composer install --no-interaction --prefer-dist

            echo "Handling permissions..."
            sudo -u deployer chmod -R 0777 storage/ bootstrap/cache

            echo "Run migrations and optimize the application..."
            sudo -u deployer php artisan migrate --force
            sudo -u deployer php artisan config:cache
            sudo -u deployer php artisan route:cache

            echo "Restart PHP-FPM to apply changes..."
            sudo systemctl restart php8.2-fpm

            echo "Clear and cache views..."
            sudo -u deployer php artisan view:clear
          EOF

          # Clean up the temporary key file
          rm -f private_key
