name: Laravel Backend Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $USERNAME@$SERVER_IP << 'EOF'
            cd /var/www/chatbots/backend

            # Check if the repository is already cloned
            if [ ! -d ".git" ]; then
              sudo -u deployer git clone https://github.com/hosseinmirzapur/chatbot-manager.git .
            else
              sudo -u deployer git pull origin main
            fi
            sudo -u deployer cp /var/www/chatbots/.env /var/www/chatbots/backend/.env

            # Install dependencies
            sudo -u deployer composer install --no-interaction --prefer-dist

            # Run migrations and optimize the application
            sudo -u deployer php artisan migrate --force
            sudo -u deployer php artisan config:cache
            sudo -u deployer php artisan route:cache

            # Restart PHP-FPM to apply changes (optional)
            sudo systemctl restart php8.2-fpm

            # Clear and cache views (optional)
            sudo -u deployer php artisan view:clear
          EOF

          # Clean up the temporary key file
          rm -f private_key
