name: Laravel Backend Workflow

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH to server and deploy
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          echo "$SSH_PRIVATE_KEY" | tr -d '\r' > private_key
          chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key $USERNAME@$SERVER_IP << 'EOF'
            cd /var/www/chatbots/backend

            git pull git@github.com:hosseinmirzapur/chatbot-manager.git .

            docker compose -f ./deployment/docker-compose.yml down
            docker compose -f ./deployment/docker-compose.yml up -d --build

            sleep 5

            docker compose -f ./deployment/docker-compose.yml exec chatbots-api php artisan migrate --force
          EOF

          # Clean up the temporary key file
          rm -f private_key
